### PR TITLE
Address lookup

### LINKED ISSUE #29: Hook up Google Maps address lookup in the ClickableMap component
We need to allow the user to enter an address and then use Google Maps API to lookup the geolocation.  Note that the [ClickableMap component](https://github.com/CV19Assist/app/blob/master/src/components/ClickableMap.js) is used on request help and the sign up screens. On the sign up screen, we also need to fill in the discrete address fields, if possible.

image

### LINKED ISSUE #85: The request page shows an error when creating a request for a non-logged in user
**Describe the bug**

1. Create a new request without logging in.
2. The console sometimes logs an error about [this line](https://github.com/CV19Assist/app/blob/cf28f724e002dc497fbf70dedc4479bc3697dca5/src/routes/NewRequest/components/NewRequestPage/NewRequestPage.js#L328).

### LINKED ISSUE #94: Restrict the google maps API key to the CV19 domains
Currently, the prod site allow access from anywhere because I mistakenly switched to a server side geocoding library which doesn't support domain-based restrictions.  The `ClickableMap` component needs to use a client-side library so we can restrict usage based on domain.

### PR DESCRIPTION
**Pull request by thebitguru**
### Description

1. Allow user to enter address on the new request and volunteer sign up pages (#29).
1. Switch to browser-based geocoding library to support domain restriction (#94).
1. Fix responsive styling of results on the search page.
1. Fix `.length` error on new request page reported in #85.
1. Upgrade a few of the older packages.

### Relevant Tickets

- closes #29, #85 and #94

### Screenshots (if appropriate)

Address completion on the new request page.
image

Address completion on the new volunteer signup page.
image

### CODE REVIEW

File: src/components/ClickableMap/ClickableMap.js [hunk 1]
```diff
@@ -198,50 +205,106 @@ function ClickableMap({ onLocationChange, locationInfo }) {
...
   }
 
+  function handlePlaceChange(address) {
+    setCurrentPlaceLabel(address);
+  }
+
+  function handlePlaceSelect(_event, selection) {
+    if (!selection) return;
+
+    geocodeByAddress(selection.description)
```
Comment (prescottprue) [inline src/components/ClickableMap/ClickableMap.js]: Did you do promise chaining over async/await here for a particular reason? i.e.

```js
async function handlePlaceSelect(_event, selection) {
  if (!selection) return;
  try {
    const [address] = await geocodeByAddress(selection.description)
    const { lat: latitude, lng: longitude } = await getLatLng(address)
    map.setZoom(15);
    setLocation({ latitude, longitude });
  } catch(err) {
    // eslint-disable-next-line no-console
    console.error('Failed to get the location from address:', error.message);
    showError('Failed to get the location from address.');
    Sentry.captureException(err)
  }
}
```

Comment (prescottprue) [reply src/components/ClickableMap/ClickableMap.js]: Ahh - just noticed the docs of react-places-autocomplete uses the chaining in there example. We can leave if you want

File: src/containers/Navbar/AccountMenu.js [hunk 2]
```diff
@@ -56,8 +48,15 @@ function AccountMenu() {
         transformOrigin={{ vertical: 'top', horizontal: 'right' }}
         open={Boolean(anchorEl)}
         onClose={closeAccountMenu}>
-        <MenuItem onClick={goToMyRequests}>My Requests</MenuItem>
-        <MenuItem onClick={goToAccount}>Account</MenuItem>
+        <MenuItem
```
Comment (prescottprue) [inline src/containers/Navbar/AccountMenu.js:51]: Nice change! This is how it should be so it uses an `a`

File: src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js [hunk 3]
```diff
@@ -61,6 +60,7 @@ export default function useNewRequestPage() {
       alert('Please select a location by clicking on the map above.'); // eslint-disable-line no-alert
       return;
     }
+    delete requestLocation.lookedUpAddress;
```
Comment (prescottprue) [inline src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js]: This works for now, but I personally usually avoid using delete since it is modifying an existing object which can sometimes have unintended consequences. I usually create a new object without that value, and if it is only one needing to be removed, you can use rest spread

File: src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js [hunk 4]
```diff
@@ -107,25 +107,14 @@ export default function useNewRequestPage() {
...
-          uid: user.uid,
-          firstName: profile.firstName,
-          displayName: profile.displayName,
-        };
-        requestPublicInfo.createdByInfo = userInfo;
-      }
+      userInfo = {
+        uid: user.uid,
+        firstName: profile.firstName,
+        displayName: profile.displayName,
```
Comment (prescottprue) [inline src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js]: Should we do `|| ''` here to handle the case of no display name like you were mentioning happens on email login?

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js [hunk 5]
```diff
@@ -63,7 +64,7 @@ function NewUser() {
       try {
         const ref = firestore.doc(`${USERS_COLLECTION}/${user.uid}`);
         // Call it once because this will throw the permission exception.
-        await ref.get();
+        setUserData(await ref.get());
```
Comment (prescottprue) [inline src/routes/NewUser/components/NewUserPage/NewUserPage.js:67]: Can we not do the single get and use the data in both state updates? Or is that what you are trying to say in the comment right above? Since the first one errors?

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js [hunk 6]
```diff
@@ -94,12 +95,67 @@ function NewUser() {
...
+   */
+  function setValueIfNotAlreadySet(
+    fieldName,
+    allFieldValues,
+    googleResultComponent,
+    addressType,
+    addressTypeFormat = 'long_name',
+  ) {
+    if (
+      googleResultComponent.types.indexOf(addressType) !== -1 &&
```
Comment (prescottprue) [inline src/routes/NewUser/components/NewUserPage/NewUserPage.js]: We can use includes like so: `googleResultComponent.types.includes(addressType)`

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js [hunk 7]
```diff
@@ -94,12 +95,67 @@ function NewUser() {
...
+        setValueIfNotAlreadySet('city', values, component, 'locality');
+        setValueIfNotAlreadySet(
+          'state',
+          values,
+          component,
+          'administrative_area_level_1',
+          'short_name',
+        );
+        setValueIfNotAlreadySet('zipcode', values, component, 'postal_code');
+        if (component.types.indexOf('street_number') !== -1) {
```
Comment (prescottprue) [inline src/routes/NewUser/components/NewUserPage/NewUserPage.js]: Same here, if you are just checking for existinence instead of finding the actual index, we can use includes:

```js
component.types.includes('street_number')
```

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js [hunk 8]
```diff
@@ -140,12 +196,20 @@ function NewUser() {
...
     if (!userLocationInfo) {
       alert('Please select a location above.'); // eslint-disable-line no-alert
       return;
     }
 
-    const userUpdates = { ...values, ...userLocationInfo };
+    delete userLocationInfo.lookedUpAddress;
+
+    // Default the displayName if it isn't already set (e.g., when signing up using email).
+    if (userData.get('displayName') === null) {
```
Comment (prescottprue) [inline src/routes/NewUser/components/NewUserPage/NewUserPage.js]: We might want to go with `!userData.get('displayName')` to handle other falsey cases such as when we have set the displayName to an empty string

File: src/utils/geo.js [hunk 9]
```diff
@@ -76,3 +76,32 @@ export function scrambleLocation(center, radiusInMeters) {
...
+ * Maps api. This assumes that the Google Maps API is already loaded and available globally as
+ * window.google.maps.
+ * @param {Number} latitude Latitude
+ * @param {Number} longitude Latitude
+ */
+export async function reverseGeocode(latitude, longitude) {
+  if (!window.google?.maps?.Geocoder) {
+    // eslint-disable-next-line no-console
+    console.error('Google Maps API not found.');
+    return null;
```
Comment (prescottprue) [inline src/utils/geo.js:93]: We may want to pass this case along to analytics or Sentry so that we know how often this is happening. It can happen in the case of the client blocking these types of requests using a browser extensions like Ghostery

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js [hunk 10]
```diff
@@ -94,12 +95,67 @@ function NewUser() {
...
+  }
+
+  function handleSetUserLocationInfo(locationInfo) {
+    setUserLocationInfo(locationInfo);
+    const result = locationInfo.lookedUpAddress;
+    if (result) {
+      const values = getValues();
+      let streetNumber = '';
+      let streetAddress = '';
+      result.address_components.forEach((component) => {
```
Comment (prescottprue) [inline src/routes/NewUser/components/NewUserPage/NewUserPage.js:136]: In the future we may want to switch to using `reduce` to build a single object so we aren't potentially doing multiple state updates for a single address lookup (due to the for loop). Seems like you are handling that with the setting only if the value doesn't exist, but just wanted to note

File: src/components/ClickableMap/ClickableMap.js [hunk 11]
```diff
@@ -198,50 +205,106 @@ function ClickableMap({ onLocationChange, locationInfo }) {
...
+      .then((results) => getLatLng(results[0]))
+      .then((latLng) => {
+        map.setZoom(15);
+        setLocation({ latitude: latLng.lat, longitude: latLng.lng });
+      })
+      .catch((error) => {
+        showError('Failed to get the location from address.');
+        // eslint-disable-next-line no-console
+        console.error('Error', error);
```
Comment (prescottprue) [inline src/components/ClickableMap/ClickableMap.js]: We could add a `Sentry.captureException` to this error case so the error goes to Sentry

**Review by prescottprue — APPROVED** [review]
Just a few small comments on patterns, but should be good to merge regardless

File: src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js (hunk 3 above)
Comment (thebitguru) [reply src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js]: Fixed.

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js (hunk 6 above)
Comment (thebitguru) [reply src/routes/NewUser/components/NewUserPage/NewUserPage.js]: You are going to make me switch this behavior! Updated. 😀

File: src/utils/geo.js (hunk 9 above)
Comment (thebitguru) [reply src/utils/geo.js:93]: Good point.  I did Sentry integration after this change so didn't account for it here.  There are a few other Google Maps places where Sentry errors would be helpful.

File: src/components/ClickableMap/ClickableMap.js (hunk 1 above)
Comment (thebitguru) [reply src/components/ClickableMap/ClickableMap.js]: Updated

File: src/routes/NewUser/components/NewUserPage/NewUserPage.js (hunk 10 above)
Comment (thebitguru) [reply src/routes/NewUser/components/NewUserPage/NewUserPage.js:136]: Good point, I wasn't thinking about the state updates.  I won't fix this specific scenario for now, but will keep it in mind going forward.

File: src/components/ClickableMap/ClickableMap.js [hunk 12]
```diff
@@ -78,23 +87,20 @@ function ClickableMap({ onLocationChange, locationInfo }) {
   const { showSuccess, showError } = useNotifications();
   const [map, setMap] = useState(null);
   const [detectingLocation, setDetectingLocation] = useState(false);
+  const [currentPlaceLabel, setCurrentPlaceLabel] = React.useState('');
```
Comment (prescottprue) [inline src/components/ClickableMap/ClickableMap.js]: useState is already imported, so we shouldn't need to do `React.useState`

File: src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js [hunk 13]
```diff
@@ -61,6 +60,8 @@ export default function useNewRequestPage() {
       alert('Please select a location by clicking on the map above.'); // eslint-disable-line no-alert
       return;
     }
+    const loc = { ...requestLocation };
```
Comment (prescottprue) [inline src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js]: we could also do:

```js
const { lookedUpAddress, ...loc } = requestLocation
```

**Review by prescottprue — APPROVED** [review]
Looks great!

File: src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js (hunk 13 above)
Comment (thebitguru) [reply src/routes/NewRequest/components/NewRequestPage/useNewRequestPage.js]: Oh, I didn't know we could do this!
